# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "owsi-core.vagrant"

  
  config.vm.network "private_network", type: "dhcp"

  # override "default" vagrant vm name
  config.vm.define "owsi-core_vagrant" do |named_vm|
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
    v.memory = 2048
    v.name = "owsi-core_vagrant"
  end

  config.vm.provision :shell do |shell|
    shell.inline = "/bin/true"
  end
end
